name: SimplifyQA Pipeline Execute

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: registry.devopsark.com/simplifyqa/pipeline-executor/v2:v5.27.1
  INPUT_PIPELINEID: 120
  INPUT_APIKEY: U2FsdGVkX1/wVFa+3VhSCg0DNrVQD0WEJmTqhYZdR7AmqpoQshrKXpgNJ7j+k/Zn4KsG3udSzMGkTjL7kxxrlSuTjOc9qcT+75WbCYpkLiWybwtiRe/ZQJUoaojMhzjs8hQFyPes1V0U8d1Wz3Qv/aFQHFi+3vsXBDTO1G3MlNh3gLDnbE54fZ7KDZC80irjFC/w04OhDiO+r+8X/Ntbjz+HbbVc78iKJa7XC35+S3dMIfdSjOJT7rCgS1Xnw+HT7Qvxvac/dzXrI+WQ9YN/0VkPDH/DRxtGaxXB1eLKoVO5Q0mNQ6Hfz4vcTnAVVX8pWSUo0vlnPAnEu+V05mjFMpl4FLHxpiRL+7ax1BJyy92p6U5TkpdLxGoUMxkUJEKbGvh1/jJTYGv2+Lb7GkF0mtWGZHuh/wTn0ckiyF+czOM=
  INPUT_THRESHOLD: 20
  INPUT_VERBOSE: true
  INPUT_MAXRETRIES: 0
  INPUT_RETRYINTERVAL: 20
  INPUT_APITIMEOUT: 1000

jobs:
  execute:
    name: Execute SimplifyQA Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin registry.devopsark.com

      - name: Pull Docker Image
        run: docker pull ${{ env.DOCKER_IMAGE }}

      - name: Run Pipeline Executor
        run: |
          docker run --rm \
            -e PIPELINEID="${{ env.INPUT_PIPELINEID }}" \
            -e APIKEY="${{ env.INPUT_APIKEY }}" \
            -e APIURL="${{ env.INPUT_APIURL }}" \
            -e THRESHOLD="${{ env.INPUT_THRESHOLD }}" \
            -e VERBOSE="${{ env.INPUT_VERBOSE }}" \
            -e MAXRETRIES="${{ env.INPUT_MAXRETRIES }}" \
            -e RETRYINTERVAL="${{ env.INPUT_RETRYINTERVAL }}" \
            -e APITIMEOUT="${{ env.INPUT_APITIMEOUT }}" \
            "${{ env.DOCKER_IMAGE }}"
